In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Plantilla de Pre-Procesado

In [4]:
#Apertura de archivo csv a un dataframe de pandas

#revisar la ruta para tu caso particular
ruta = "c:\\Users\\jrgui\\Documents\\GitHub\\Machine_Learning\\Pre_Procesamiento\\datasets\\data.csv"
dataset = pd.read_csv(ruta)
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [111]:
#Sacar las variables independientes, todas la columnas menos la ultima

X = dataset.iloc[:,:-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [112]:
# Sacar la variable dependientes
Y = dataset.iloc[:,3].values
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [113]:
#Tratamientos datos faltantes

#Llena el dato faltante de la columna Age con la media o el promedio
dataset['Age'].fillna(dataset['Age'].mean().round(0), inplace=True)
#Llena el dato faltante de la columna salary con la media o el promedio
dataset['Salary'].fillna(dataset['Salary'].mean().round(1), inplace=True)

dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  63777.8       Yes
5   France  35.0  58000.0       Yes
6    Spain  39.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [114]:
# Codificacion de Datos Categoricos

#importa la libreria de preprocesamiento de sklearn
from sklearn import preprocessing

#tomo nuevamente los valores sin datos faltantes
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:,3].values

#inicializa labelencoder
labelencoder_x = preprocessing.LabelEncoder()

#cambio los nombre de los paises en categorias ordinales
X[:,0] = labelencoder_x.fit_transform(X[:,0])
X

#esta categorias nuevas no son del todo utiles, ya que se generan una 
#gerarquia 1 es mayor que 0, 2 es mayor que 0 y 1, estos nos puede
#traer problemas al usar un modelo de ML.


array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.8],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [115]:
#Ahorra se debe pasar a variable dummy con onehotencoder
#tranforma el arreglo en un arreglo de numpy
data = np.array(X)
# Separar la primera columna del resto
first_column = data[:, 0].reshape(-1, 1)
other_columns = data[:, 1:]

# Crear el codificador OneHotEncoder
encoder = preprocessing.OneHotEncoder(sparse_output=False)

# Ajustar y transformar la primera columna
first_column_encoded = encoder.fit_transform(first_column)

# Concatenar la columna codificada con las demás columnas
X = np.hstack((first_column_encoded, other_columns))

X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.8],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [116]:
#tranformar los valores de Y, en este caso al ser yes o no, 
#se puede usar solo labelencoder, la deja 0 ó 1

#inicializa labelencoder
labelencoder_y = preprocessing.LabelEncoder()
#se tranforma la columna y a variable categorica
Y = labelencoder_y.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [117]:
#Division de Datos - entrenamiento y validacion

#herramienta para dividir los datos
from sklearn.model_selection import train_test_split

#divide los datos en 20% para la validacion y se colocar una semilla para hacer la division
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2, random_state=0)

print("y_train",y_train,"\n", "X_train",X_train )
print("y_test",y_test,"\n","X_test",X_test)



y_train [1 1 1 0 1 0 0 1] 
 X_train [[0.0 1.0 0.0 40.0 63777.8]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 39.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
y_test [0 0] 
 X_test [[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 50.0 83000.0]]


In [118]:
# Escalado de Variables - Estandarizacion y Normalizacion

#Es preferible utilizalo en algortimos que usan el calculo de distancia - pitagoras 

#Estandarizacion
sc_X = preprocessing.StandardScaler()

X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

print("X_train",X_train,"\n", "X_test",X_test )

X_train [[-1.          2.64575131 -0.77459667  0.25819889  0.12381682]
 [ 1.         -0.37796447 -0.77459667 -0.25819889  0.46175601]
 [-1.         -0.37796447  1.29099445 -1.97952482 -1.53093364]
 [-1.         -0.37796447  1.29099445  0.0860663  -1.11142003]
 [ 1.         -0.37796447 -0.77459667  1.63525964  1.72029684]
 [-1.         -0.37796447  1.29099445 -0.0860663  -0.16751441]
 [ 1.         -0.37796447 -0.77459667  0.94672926  0.98614802]
 [ 1.         -0.37796447 -0.77459667 -0.60246408 -0.48214962]] 
 X_test [[-1.          2.64575131 -0.77459667 -1.46312704 -0.90166323]
 [-1.          2.64575131 -0.77459667  1.97952482  2.13981045]]
